language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: kRdwowztBY+4Rsy7FcWWsbbZCyAwMjyBlv2hQnolBrkem9pO6b505458r1x191PXZCjGGPqbvbXj6ltTOO7mmtQ2z1CwMqTNA1d7E1E5gfcT54fUkq3oJY1eZOvLpkuiA64/jFHm09eaqP29RAq74ZUXte2agm3a46GyasXAy9nOnu8T9fIOodLJqO0GjHya7WlYcX/pL560l1JSkCBvcNeEWPOVvtyvuiGwhGJQmhQfhiZPlVXPFNmkhVCidrrl1+i0vQwp1ElYs+zgjJI3mBHmV/rpfKH31TsB3HT4FCLfXD9aQWI6iHnxzeQqIzYbPVH1PNj9WcsbT/Vh5GloP4zVjrhRcw0YBawSnsipF5CXlZvlKL7IUyd4v/jmhmw0FUVr4fgKgoOX2JfUT47/IFq14zJ8EfVtT8gWXV2vWmfYGfjO/K63gfXWlAT6DzeVls85/bqflDimGL3ZgIGJ2iDaKHukOp7WLo+GQOI0xXD33t7FW7uMe5GfS0L+n09KWobCz2NcRMHwi1SVpJkXv20gNQd4q6Yyw5FdGEDvIsxWkpTuiH412ysJy5s3JEViFpsnh2x0afg2rS12Mt5C2FeghQnlRBK0IabdBoN+Wab58YBGkwrOEZntNCf73p58o1EH7XKA/5a7NZ+rgfSnJUPaOOQP813cTUlsoHW30JI=
  app: https://morning-caverns-25715.herokuapp.com/
  run: rails db:migrate
