language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: k55saGW4A8ZYVSw/3WMr/BnisCU0JRIvkwqgRusJvJTgs3YoJKh1zMqneetjDc/lcQDfmaaYuxybOO6Mx6U8Ces8wOmzk+JztmbiDG3hUEL5NvwqijX5Lr/ejjw24qm6q+2JUgeEdfIWSApOs+mDR7VKmDlMaAUxKmjLDpp8JQAh9P7QDEuMubWWMYg3F4mZhFM35hSy80Qz8Hhm8lMWNIq39OkBl1L1RdSGABJM+flzhGQoB+hsZxq2XhjTR6XNC8sdJlf0Cbb2vMNZTQAQmTDfUFavOk8TBy+IiO2QMQLBoTlTUI5GUeORfEBZBK2y1SGLgf4kCyRnbhoqsf0l369zIgwuEqXy2fzwtwhz4UsF4h2TQOrM2RbmtIbzyUP5pqF0HI4zy8KN6nUzuBEGIuSFFN3/pjUgIn4qZx43diSdIPW8FLT3d3PhzYJfJbqWlJuNVSi39mDggjyB1lwdX0fXOyZXY0+faCw9vU/udr4WnGBFCTAWSZukLTFt9pl+Y/xnuAqb0c3qZdlnmYEEfwKke7wnWAtmo8WT7p5pWEww5U+Q1Sm31ftToYYV05m0o+z1YrzneIIWdCY3c4GF13BTQBq13hktCkiRkpW29+qbUz3NgOkNrz178dMS8JgWKACpkJ9UgcvdKrqbkmAfsbOYSf6JaY4ek6wA8AetH10=
  app: morning-caverns-25715
  run: rails db:migrate
  on:
    repo: sami-p/viewing_party
    branch: main
env:
  global:
    secure: ka/untjVc8qJ4jfOv3KxcfrghLU9k2x4sFkp40zSVcmukU8Nj1DG3W1msMJxL/LS1oP1ZSjQoVrxoOt1sOnaItEdfe7RFW+OMIHDJkeB5rND3ocq2W9GCQDh+rTR972HCUN8KrIasfeW18SO93hzrp8ztj5Qf2SfntIQS7PH5HYS6g13/otLaq9TOSzFBK477v/7H9f+ygLMJK/VthnAz5cGf9IXueoFJ1utgCqX5xR+jrNA4Umkf7hzGwji2c0W31OdScpA1LGJof6KCST7cy6m1zil80ATthzLjLQrdxCmY+azSg2ubbyB8kyJZ2PDvz3trUjgABmyUZ23NRPGKijM8XjICneMsVsiMTb6G2Bzm7IxE+vovGMCP7wDjeDXSDcgG2QYukbiZUcnI0g2QeXbwZgBP781laifiiZmDX/g/s0EEmLnTR/MZqtyuLBa6d0hDs64tkjmBDZ/7fMEHu8E7UtqFxD8NVd3mN0gZjYKFgOxj2Xj7A9A6wTcbE/Jq/GPul44AmuAwfDbOhjAPHXiSPP2PL+v5MBLp16vVfaRQ+8i0ncESpuDqwwKJS/6fCsBZMDsspOLm3FGDVdS5AD5TGpgeC9coHE3Jxg+SpuQz6Hmx8a5pbVh/LTBcdGsr/BYBsxoMur6bEqXRdaMOoJGSoC2rPbPaj0/4bjrHqs=
